config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resource :timeline, only: [:show]

  resources :posts

  resource :profile, only: [:show, :edit, :update]

  resources :accounts, only: [:show] do
    resources :follows, only: [:create]
    resources :unfollows, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { maximum: 140 }

  belongs_to :user

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def auther_name
    user.display_name
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :nickname, presence: true
  validates :introduction, length: { maximum: 200 }
  validates :nickname, length: { maximum: 20 }
  validates :nickname, format: { with: /\A[a-zA-Z]+\z/ }
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_one :profile, dependent: :destroy

  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships, source: :following

  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships, source: :follower

  def has_written?(post)
    posts.exists?(id: post.id)
  end

  def prepare_profile
    profile || build_profile
  end

  def follow!(user)
    user_id = get_user_id(user)
    following_relationships.create!(following_id: user_id)
  end

  def unfollow!(user)
    user_id = get_user_id(user)
    relation = following_relationships.find_by!(following_id: user_id)
    relation.destroy!
  end

  def has_followed?(user)
    following_relationships.exists?(following_id: user.id)
  end

  def display_name
    profile&.nickname || self.email.split('@').first
  end

  private
  def get_user_id(user)
    if user.is_a?(User)
      user.id
    else
      user
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @user = User.find(params[:id])
    if @user == current_user
      redirect_to profile_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.follow!(params[:account_id])
    redirect_to account_path(params[:account_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @posts = Post.includes(user: :profile).all
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post), notice: '保存できました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

  private
  def post_params
    params.require(:post).permit(:content)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @profile = current_user.profile
  end

  def edit
    @profile = current_user.prepare_profile
  end

  def update
    @profile = current_user.build_profile
    @profile.assign_attributes(profile_params)
    if @profile.save
      redirect_to profile_path, notice: '更新しました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :nickname,
      :introduction,
      :blogurl
    )
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :authenticate_user!

  def show
    user_ids = current_user.followings.pluck(:id)
    @posts = Post.includes(user: :profile).where(user_id: user_ids)
  end
end

app/controllers/unfollows_controller.rb
class UnfollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.unfollow!(params[:account_id])
    redirect_to account_path(params[:account_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tabs_helper.rb
module TabsHelper
  def add_active_class(path)
    'active' if current_page?(path)
  end
end

app/views/accounts/show.html.haml
.container
  = render 'commons/profile', user: @user
  .d-flex.justify-content-end
    = link_to :back do
      .btn.btn-secondly.me-3
        %p 戻る
    - if @user == current_user
      = link_to edit_profile_path do
        .btn.btn-primary
          %p 編集
    - else
      - if current_user&.has_followed?(@user)
        = link_to account_unfollows_path(@user), data: {method: 'post'} do
          .btn.btn-primary
            %p フォローを解除
      - else
        = link_to account_follows_path(@user), data: {method: 'post'} do
          .btn.btn-primary
            %p フォロー
  %h5.mb-3 記事一覧
  - @user.posts.each do |post|
    = render 'commons/post', post: post

app/views/commons/_post.html.haml
= link_to post_path(post) do
  .card.mb-3
    .card-body
      %p
        = post.content
      %p
        = post.display_created_at
      %p.mt-3
        = image_tag 'default-avatar.png', class: 'default-avatar'
        = post.auther_name

app/views/commons/_posts.html.haml
%ul.nav.nav-tabs.justify-content-center.mb-3
  %li.nav-item.me-5
  = link_to '新着記事一覧', root_path, class: "nav-link #{add_active_class(root_path)}"
  %li.nav-item
    = link_to 'タイムライン', timeline_path, class: "nav-link #{add_active_class(timeline_path)}"

- @posts.each do |post|
  = render 'commons/post', post: post

app/views/commons/_profile.html.haml
%h5.mb-3 公開情報
%table.table.table-bordered
  %tbody
    %tr.text-center
      %th ユーザー名
      %td
        - if user.profile.present?
          = user.profile.nickname
    %tr.text-center
      %th プロフィール
      %td
        - if user.profile.present?
          = user.profile.introduction
    %tr.text-center
      %th ブログURL
      %td
        - if user.profile.present?
          = user.profile.blogurl

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Miniblog
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.bg-body-tertiary.mb-3
      .container-fluid
        = link_to root_path do
          .navbar-brand MiniBlog
        - if user_signed_in?
          .dropdown
            .dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", type: "button"}
              = image_tag 'default-avatar.png', class: 'default-avatar'
            %ul.dropdown-menu.dropdown-menu-end
              %li.text-center
                = link_to 'プロフィール', profile_path
              %li.text-center
                = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
        - else
          = link_to 'ログイン', new_user_session_path, class: 'btn btn-primary'
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{class: key}= value
    = yield

app/views/posts/_form.html.haml
.container
  %ul
    - @post.errors.full_messages.each do |message|
      %li
        = message
  %h5.mb-3 投稿内容(140字以内)
  = form_with(model: @post, local: true) do |f|
    %div
      = f.text_area :content, class: 'form-control'
    .d-flex.justify-content-end.mt-3
      = link_to :back do
        .btn.btn-secondly.me-3
          %p 戻る
      = f.submit '保存', class: 'btn btn-primary'

app/views/posts/edit.html.haml
= render 'form', post: @post

app/views/posts/index.html.haml
.container
  = render 'commons/posts'

  .d-flex.justify-content-end
    = link_to new_post_path do
      .btn.btn-primary.mb-3
        %div 新規作成

app/views/posts/new.html.haml
= render 'form', post: @post

app/views/posts/show.html.haml
.container
  .card.mb-3
    .card-body
      %p
        = @post.content
      %p
        = @post.display_created_at
      %p.mt-3
        = link_to account_path(@post.user) do
          = image_tag 'default-avatar.png', class: 'default-avatar'
          = @post.auther_name

  .d-flex.justify-content-end
    = link_to :back do
      .btn.btn-secondly
        %p 戻る
    - if user_signed_in? && current_user.has_written?(@post)
      = link_to edit_post_path(@post) do
        .btn.btn-primary.me-3.ms-3
          %p 編集
      = link_to post_path(@post), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' } do
        .btn.btn-danger
          %p 削除

app/views/profiles/edit.html.haml
.container
  %ul
    - @profile.errors.full_messages.each do |message|
      %li
        = message
  = form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f|
    %div.mb-3
      = f.label :nickname, 'ユーザー名(アルファベットのみ、空白禁止、20文字以内)', class: 'form-label'
      = f.text_field :nickname, class: 'form-control'
    %div.mb-3
      = f.label :introduction, 'プロフィール(200文字以内)', class: 'form-label'
      = f.text_area :introduction, class: 'form-control'
    %div.mb-3
      = f.label :blogurl, ' ブログURL', class: 'form-label'
      = f.text_area :blogurl, class: 'form-control'
    .d-flex.justify-content-end.mt-3
      = link_to :back do
        .btn.btn-secondly.me-3
          %p 戻る
      = f.submit '保存', class: 'btn btn-primary'

app/views/profiles/show.html.haml
.container
  = render 'commons/profile', user: current_user
  .d-flex.justify-content-end
    = link_to :back do
      .btn.btn-secondly.me-3
        %p 戻る
    = link_to edit_profile_path do
      .btn.btn-primary
        %p 編集
  %h5.mb-3 記事一覧
  - current_user.posts.each do |post|
    = render 'commons/post', post: post

app/views/timelines/show.html.haml
.container
  = render 'commons/posts'